export const commonExercises = [
  "Barbell Bench Press",
  "Squat",
  "Deadlift",
  "Overhead Press",
  "Bent Over Row",
  "Pull Up",
  "Chin Up",
  "Dumbbell Bench Press",
  "Incline Dumbbell Press",
  "Dumbbell Fly",
  "Cable Crossover",
  "Push Up",
  "Dip",
  "Leg Press",
  "Leg Extension",
  "Leg Curl",
  "Lunge",
  "Calf Raise",
  "Lat Pulldown",
  "Dumbbell Row",
  "Seated Cable Row",
  "Face Pull",
  "Bicep Curl",
  "Hammer Curl",
  "Tricep Extension",
  "Tricep Pushdown",
  "Skull Crusher",
  "Lateral Raise",
  "Front Raise",
  "Shoulder Press",
  "Upright Row",
  "Plank",
  "Crunch",
  "Leg Raise",
  "Russian Twist"
];
